--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/nfs/cluster/sce/sesh/closed/NVIDIA/build/inference/tools/submission/submission_checker.py", line 3317, in <module>
    sys.exit(main())
  File "/nfs/cluster/sce/sesh/closed/NVIDIA/build/inference/tools/submission/submission_checker.py", line 3152, in main
    results, systems = check_results_dir(
  File "/nfs/cluster/sce/sesh/closed/NVIDIA/build/inference/tools/submission/submission_checker.py", line 2066, in check_results_dir
    log.error(
Message: "Root contains files outside division folder %s. You can use '--skip-extra-files-in-root-check' to skip this check temporarily"
Arguments: ('closed', ['mlperf-inference-Oracle-submission.tar.gz', 'mlperf-inference-Oracle-submission.sha1'])
[2025-02-28 11:31:41,407 submission_checker.py:3167 INFO] ---
[2025-02-28 11:31:41,407 submission_checker.py:3173 INFO] ---
[2025-02-28 11:31:41,407 submission_checker.py:3176 ERROR] NoResults root
[2025-02-28 11:31:41,407 submission_checker.py:3262 INFO] ---
[2025-02-28 11:31:41,407 submission_checker.py:3263 INFO] Results=0, NoResults=1, Power Results=0
[2025-02-28 11:31:41,407 submission_checker.py:3270 INFO] ---
[2025-02-28 11:31:41,407 submission_checker.py:3271 INFO] Closed Results=0, Closed Power Results=0

[2025-02-28 11:31:41,407 submission_checker.py:3276 INFO] Open Results=0, Open Power Results=0

[2025-02-28 11:31:41,407 submission_checker.py:3281 INFO] Network Results=0, Network Power Results=0

[2025-02-28 11:31:41,407 submission_checker.py:3286 INFO] ---
[2025-02-28 11:31:41,407 submission_checker.py:3288 INFO] Systems=0, Power Systems=0
[2025-02-28 11:31:41,407 submission_checker.py:3292 INFO] Closed Systems=0, Closed Power Systems=0
[2025-02-28 11:31:41,407 submission_checker.py:3297 INFO] Open Systems=0, Open Power Systems=0
[2025-02-28 11:31:41,407 submission_checker.py:3302 INFO] Network Systems=0, Network Power Systems=0
[2025-02-28 11:31:41,407 submission_checker.py:3307 INFO] ---
[2025-02-28 11:31:41,407 submission_checker.py:3309 ERROR] SUMMARY: submission has errors
